import Head from "next/head";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Link from "next/link";
import Navbar from "../components/Navbar";
import Sliders from "../components/Sliders";
import {
  SliderMain,
  SliderMainSettings,
  SliderOther,
  SliderOtherSettings,
  ourPartners,
} from "../data/data";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative w-full md:h-[70vh] h-[60vh] flex flex-col items-center justify-start text-center text-white bg-home-image bg-no-repeat bg-cover ">
        <Navbar />
        <div className="md:w-[770px] h-[330px] mt-12 mb-16">
          <h1 className="md:text-[72px] text-[32px] font-bold ">
            BUILDINGS IN THE METAVERSE
          </h1>
          <h5 className="font-bold mt-8 mb-12">
            LANDMARKS ARCHITECTURE FOR THE NEW HUMANITY
          </h5>
          <button className="border-2 rounded-md border-white p-2 w-[155px] h-[60px] hover:bg-white hover:text-green-600">
            <Link href="/contact">
              <p className="text-lg font-bold">Get Started</p>
            </Link>
          </button>
        </div>
      </div>
      <div className="bg-[#fafafa] mt-16 md:mt-0 ">
        <div className="md:max-w-screen-xl  w-full mx-auto flex flex-col items-center justify-center gap-y-6">
          <h2 className="text-2xl font-bold md:pt-8 pt-6 text-center">
            DISCOVER HOUSES, LANDMARKS
          </h2>
          <Sliders
            settings={SliderMainSettings}
            data={SliderMain}
            isRow={false}
          />
          <Sliders
            settings={SliderOtherSettings}
            data={SliderOther}
            isRow={true}
          />
        </div>
      </div>
      <div className="w-full flex flex-col justify-center items-center md:gap-y-20 h-[400px] md:h-[700px] p-4 md:p-0">
        <h2 className="md:text-[40px] text-xl font-bold md:pb-0 pb-4">
          OUR PARTNERS
        </h2>
        <div className="md:w-[1170px] gap-x-8  p-12 md:h-[456px] w-full h-auto flex flex-row items-center justify-between rounded-lg shadow-2xl ">
          {ourPartners.map((item, index) => (
            <div key={index} className="w-1/4 text-center gap-y-12">
              <img
                className="mx-auto pb-8 object-cover"
                src={item.imgUrl}
                alt={item.title}
              />

              <p className="md:text-xl md:font-bold">{item.title}</p>
            </div>
          ))}
        </div>
      </div>
      <Footer />
    </div>
  );
}
